### ISSUE TITLE
strange behaviour

### ISSUE THREAD

**Issue by velkyel** [CPunch/Cosmo#5]
hello,

```
for i in [0, 1, 2, 3] do
   print(i)
end
```
prints:
3
2
1
0

that is strange, why not 0 1 2 3?

**Comment by CPunch** [comment]
iterators over tables in cosmo don't guarantee order, only that each key/value pair will eventually be iterated over. Other languages like javascript have a similar behavior pattern, and changing this behavior would be more work than what is worth. 

If you need to iterate in a certain order, use a more traditional for loop style and iterate over each index

```
tbl = [0, 1, 2, 3]

for (var i = 0; i < #tbl; i++) do 
    print(tbl[i]) 
end
```
